# Generated by Django 6.0.6 on 2026-07-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='note',
            new_name='notes',
        ),
    ]
